<#
  Publishes the Zombies Guides app to the phone.

  Usage:
      .\publish.ps1
      .\publish.ps1 "added Kino der Toten"

  What it does:
    1. Rebuilds sw-shell.js (the offline file list + a fresh version stamp) so phones
       that already have the app installed pick the update up instead of serving the
       old cached copy.
    2. Commits everything and pushes to GitHub.
  GitHub Pages redeploys on its own about a minute later.

  -PurgeImages  also makes installed phones drop their cached screenshots. Only needed
                if you REPLACED an image while keeping its old filename.
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$Message = "Update guide",

    [switch]$PurgeImages
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
Set-Location $root

if (-not (Test-Path (Join-Path $root ".git"))) {
    Write-Host "This folder isn't a git repo yet — run the one-time setup first." -ForegroundColor Red
    exit 1
}

# ---- 1. regenerate the offline file list -------------------------------------------
$version = Get-Date -Format "yyyyMMdd-HHmmss"

$patterns = @("index.html", "game.html", "manifest.webmanifest",
              "maps\*.html", "css\*.css", "js\*.js", "icons\*.png", "audio\*.mp3")

$files = foreach ($p in $patterns) {
    Get-ChildItem -Path (Join-Path $root $p) -File -ErrorAction SilentlyContinue |
        ForEach-Object { $_.FullName.Substring($root.Length + 1).Replace("\", "/") }
}
# the worker must never try to cache itself
$files = $files | Where-Object { $_ -notmatch '^sw(-shell)?\.js$' } | Sort-Object -Unique

$lines = @(
    "/* GENERATED by publish.ps1 - do not edit by hand. */",
    "var SHELL_VERSION = '$version';",
    "var SHELL_FILES = ["
)
$lines += ($files | ForEach-Object { "  '$_'," })
$lines += "];"

$lines -join "`n" | Out-File -FilePath (Join-Path $root "sw-shell.js") -Encoding utf8

Write-Host "Offline list rebuilt: $($files.Count) files, version $version" -ForegroundColor Cyan

if ($PurgeImages) {
    $swPath = Join-Path $root "sw.js"
    $sw = Get-Content $swPath -Raw
    $stamp = "// media-epoch: $version"
    if ($sw -match "(?m)^// media-epoch: .*$") {
        $sw = $sw -replace "(?m)^// media-epoch: .*$", $stamp
    } else {
        $sw = $sw.TrimEnd() + "`n$stamp`n"
    }
    $sw = $sw -replace "zg-media-v\d+", "zg-media-v$([int]((Get-Date) - (Get-Date '2026-01-01')).TotalMinutes)"
    $sw | Out-File -FilePath $swPath -Encoding utf8 -NoNewline
    Write-Host "Screenshot cache will be rebuilt on phones (this re-downloads images)." -ForegroundColor Yellow
}

# ---- 2. commit + push --------------------------------------------------------------
git add -A
if ((git status --porcelain).Length -eq 0) {
    Write-Host "Nothing changed - nothing to publish." -ForegroundColor Yellow
    exit 0
}

git commit -m $Message
if ($LASTEXITCODE -ne 0) { throw "git commit failed" }

git push
if ($LASTEXITCODE -ne 0) { throw "git push failed" }

Write-Host ""
Write-Host "Published. Live in about a minute at:" -ForegroundColor Green
Write-Host "  https://scotypreston.github.io/zombies-guide/" -ForegroundColor Green
Write-Host "On the phone: close the app fully and reopen it twice to pick up the new version." -ForegroundColor DarkGray
