/* Service worker for the Zombies Guides app.
 *
 * Two caches, on purpose:
 *   zg-shell-<version>  the pages/CSS/JS/icons. Wiped and refetched on every publish.
 *   zg-media-v1         the screenshots and audio clips. Kept across publishes, because
 *                       re-downloading ~86 MB of images every time a typo is fixed is silly.
 *                       Image filenames are stable, so a stale entry means a stale file only
 *                       if that exact filename was overwritten — see purgeMedia() below.
 *
 * sw-shell.js is GENERATED by publish.ps1 and defines SHELL_VERSION + SHELL_FILES.
 */
importScripts('sw-shell.js');

const SHELL_CACHE = 'zg-shell-' + SHELL_VERSION;
const MEDIA_CACHE = 'zg-media-v1';

// ---- install: pre-cache the shell so the app opens instantly and works offline ----
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE)
      .then((cache) => Promise.allSettled(
        // allSettled, not addAll: one 404 must not sink the whole install
        SHELL_FILES.map((f) => cache.add(new Request(f, { cache: 'reload' })))
      ))
      .then(() => self.skipWaiting())
  );
});

// ---- activate: drop old shell caches, keep media ----
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('zg-shell-') && k !== SHELL_CACHE)
            .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

// A publish can tell the worker to forget specific cached images (see publish.ps1 -PurgeImages).
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'PURGE_MEDIA') {
    event.waitUntil(caches.delete(MEDIA_CACHE));
  }
});

const isMedia = (url) => /\/(img|audio)\//.test(url.pathname);

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Pages: network first, so a publish shows up as soon as you're online.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(SHELL_CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match('index.html')))
    );
    return;
  }

  // Screenshots and audio: cache first. They're big and they don't change.
  if (isMedia(url)) {
    event.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(MEDIA_CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }))
    );
    return;
  }

  // CSS/JS/icons/manifest: serve cached instantly, refresh in the background.
  event.respondWith(
    caches.match(req).then((hit) => {
      const net = fetch(req).then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(SHELL_CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => hit);
      return hit || net;
    })
  );
});
